import os


def generate_basic_code(file_path):

    extension = os.path.splitext(file_path)[1]

    if extension == ".py":
        return """# Auto generated by BlueprintAI

def main():
    pass
"""

    elif extension == ".jsx":
        return """export default function Home() {
    return <h1>BlueprintAI Generated Component</h1>;
}
"""

    elif extension == ".js":
        return """console.log("BlueprintAI Generated");"""

    else:
        return ""